stanzas:
  - type: webapp
    exec: ../dist/bin/seattlehaskell
    hosts:
      - www.seattlehaskell.com
    requires-secure: false
  - type: redirect
    hosts:
      - seattlehaskell.com
    actions:
      - host: www.seattlehaskell.com
