stanzas:
  - type: webapp
    forward-env:
      - MEETUP_API_KEY
    exec: ../dist/bin/seattlehaskell
    hosts:
      - seattlehaskell.org
    requires-secure: false
  - type: redirect
    hosts:
      - www.seattlehaskell.org
    actions:
      - host: seattlehaskell.org
