Default: &defaults
  database: seattlehaskell-org.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: seattlehaskell-org_test.sqlite3
  <<: *defaults

Staging:
  database: seattlehaskell-org_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: seattlehaskell-org_production.sqlite3
  poolsize: 100
  <<: *defaults
